package persistencia;
// Generated 27/06/2014 02:04:02 PM by Hibernate Tools 3.6.0



/**
 * Docentes generated by hbm2java
 */
public class Docentes  implements java.io.Serializable {


     private Integer idDocente;
     private String nombre;

    public Docentes() {
    }

    public Docentes(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(Integer idDocente) {
        this.idDocente = idDocente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


