package persistencia;
// Generated 18/06/2014 01:33:23 PM by Hibernate Tools 3.6.0



/**
 * Grupos generated by hbm2java
 */
public class Grupos  implements java.io.Serializable {


     private int idGrupo;
     private String nombre;
     private int idDocente;
     private int nivel;
     private int idEvaluacion;

    public Grupos() {
    }

    public Grupos(int idGrupo, String nombre, int idDocente, int nivel, int idEvaluacion) {
       this.idGrupo = idGrupo;
       this.nombre = nombre;
       this.idDocente = idDocente;
       this.nivel = nivel;
       this.idEvaluacion = idEvaluacion;
    }
   
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(int idDocente) {
        this.idDocente = idDocente;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public int getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(int idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }




}


