package persistencia;
// Generated 04-jul-2014 23:09:14 by Hibernate Tools 3.6.0



/**
 * Preguntas generated by hbm2java
 */
public class Preguntas  implements java.io.Serializable {


     private Integer idPregunta;
     private String descripcion;
     private String respuestas;

    public Preguntas() {
    }

	
    public Preguntas(String descripcion) {
        this.descripcion = descripcion;
    }
    public Preguntas(String descripcion, String respuestas) {
       this.descripcion = descripcion;
       this.respuestas = respuestas;
    }
   
    public Integer getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(Integer idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(String respuestas) {
        this.respuestas = respuestas;
    }




}


