package persistencia;
// Generated 08-jul-2014 19:01:58 by Hibernate Tools 3.6.0



/**
 * Preguntas generated by hbm2java
 */
public class Preguntas  implements java.io.Serializable {


     private Integer idPregunta;
     private String descripcion;
     private String respuestas;
     private String banco;

    public Preguntas() {
    }

	
    public Preguntas(String descripcion, String banco) {
        this.descripcion = descripcion;
        this.banco = banco;
    }
    public Preguntas(String descripcion, String respuestas, String banco) {
       this.descripcion = descripcion;
       this.respuestas = respuestas;
       this.banco = banco;
    }
   
    public Integer getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(Integer idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(String respuestas) {
        this.respuestas = respuestas;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }




}


