package persistencia;
// Generated 8/08/2014 01:54:49 PM by Hibernate Tools 3.6.0



/**
 * Registros generated by hbm2java
 */
public class Registros  implements java.io.Serializable {


     private Integer idRegistro;
     private int idAlumno;
     private String comentario;

    public Registros() {
    }

    public Registros(int idAlumno, String comentario) {
       this.idAlumno = idAlumno;
       this.comentario = comentario;
    }
   
    public Integer getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(Integer idRegistro) {
        this.idRegistro = idRegistro;
    }
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


