package persistencia;
// Generated 8/08/2014 01:54:49 PM by Hibernate Tools 3.6.0



/**
 * Resultados generated by hbm2java
 */
public class Resultados  implements java.io.Serializable {


     private Integer idResultados;
     private int idRegistro;
     private int idPregunta;
     private String answer;

    public Resultados() {
    }

    public Resultados(int idRegistro, int idPregunta, String answer) {
       this.idRegistro = idRegistro;
       this.idPregunta = idPregunta;
       this.answer = answer;
    }
   
    public Integer getIdResultados() {
        return this.idResultados;
    }
    
    public void setIdResultados(Integer idResultados) {
        this.idResultados = idResultados;
    }
    public int getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(int idRegistro) {
        this.idRegistro = idRegistro;
    }
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


